### ISSUE TITLE
Port to KK/EC/KKS

### ISSUE THREAD

**Issue by smartluo1833** [ManlyMarco/Illusion_ClothColliders#2]
Hello, Master ManlyMarco,
‘Illusion_ClothColliders’ already supports AI and HS2, can KK also get the favor of this plug-in?

I recently tried to use Unity to add fabric to the KK skirt. The effect is very good and amazing. Compared with a skeletal skirt, the fabric skirt solves the problem of dancing, squatting down and piercing the skirt into the leg. It has a more delicate performance, I was shocked. 

It would be better if KK could also use this amazing plugin.

Thank you.

**Comment by ManlyMarco** [comment]
Hello!

I can definitely port it as long as there's someone that can make a mod to test it with. Can you ping me on the Koikatsu server so we can coordinate better?

**Comment by smartluo1833** [comment]
I uploaded my cloth acc test mod for Koikatsu.
https://discord.com/channels/447114928785063977/476358846764548137/875281322099232799

**Comment by ManlyMarco** [comment]
Done and released.
